{
    parserClass="com.technophobia.substeps.parser.substepsdefinition.SubstepsParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="SubstepsDefinition"
    psiImplClassSuffix="Impl"
    psiImplPackage="com.technophobia.substeps.psi.substepsdefinition"
    psiImplPackage="com.technophobia.substeps.psi.substepsdefinition.impl"
    psiImplUtilClass="com.technophobia.substeps.psi.substepsdefinition.impl.SubstepsDefinitionPsiImplUtil"

    elementTypeHolderClass="com.technophobia.substeps.psi.substepsdefinition.SubstepsDefinitionTypes"
    elementTypeClass="com.technophobia.substeps.psi.substepsdefinition.SubstepsDefinitionElementType"
    tokenTypeClass="com.technophobia.substeps.psi.substepsdefinition.SubstepsDefinitionTokenType"

}

substepsFile ::= item_*

private item_ ::= (definition|stepLine|GENERAL_DIRECTIVE|COMMENT|CRLF)
definition ::= (DEFINITION_LABEL DEFINITION_TEXT?) { mixin="com.technophobia.substeps.psi.substepsdefinition.impl.SubstepDefinitionNamedElementImpl"
    implements="com.technophobia.substeps.psi.substepsdefinition.SubstepDefinitionNamedElement" methods=[definitionText getNameIdentifier getName setName]}

stepLine ::= (STEP) | STEP { implements="com.intellij.psi.ContributedReferenceHost" methods=[definitionForStepText getReferences]}