{
    parserClass="com.technophobia.substeps.parser.substepsdefinition.SubstepsParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="SubstepsDefinition"
    psiImplClassSuffix="Impl"
    psiImplPackage="com.technophobia.substeps.psi.substepsdefinition"
    psiImplPackage="com.technophobia.substeps.psi.substepsdefinition.impl"

    elementTypeHolderClass="com.technophobia.substeps.psi.substepsdefinition.SubstepsDefinitionTypes"
    elementTypeClass="com.technophobia.substeps.psi.substepsdefinition.SubstepsDefinitionElementType"
    tokenTypeClass="com.technophobia.substeps.psi.substepsdefinition.SubstepsDefinitionTokenType"
}

substepsFile ::= item_*

private item_ ::= (definition|STEP|GENERAL_DIRECTIVE|COMMENT|CRLF)
definition ::= (DEFINITION_LABEL DEFINITION_TEXT?)